Repository Financial-Times/origami-navigation-service, pull requests merged in 2022-01, with the labels that each got.

#290 Update links.yaml
  data/links.yaml
Labels: service

#292 Update navigation.yaml
  data/navigation.yaml
Labels: service

#293 Update navigation.yaml
  data/navigation.yaml
Labels: service, release:patch

#291 update package-lock.json via `npm update`
  package-lock.json
Labels: service, release:patch

#294 Update links.yaml
  data/links.yaml
Labels: release:patch

#295 Update navigation.yaml
  data/navigation.yaml
Labels: service, release:patch

#296 Update links.yaml
  data/links.yaml
Labels: service, release:patch

#297 Update links.yaml
  data/links.yaml
Labels: service, release:patch

#298 Update navigation.yaml
  data/navigation.yaml
Labels: service, release:patch
