Repository Financial-Times/origami-navigation-service, pull requests merged in 2024-01, with the labels that each got.

#844 Update navigation.yaml
  data/navigation.yaml
Labels: service, release:patch

#848 Update navigation.yaml
  data/navigation.yaml
Labels: service, release:patch

#851 Update navigation.yaml
  data/navigation.yaml
Labels: service, release:patch

#852 Add missing US menu items
  data/navigation.yaml
Labels: service

#854 Add FT App & FT Edit to tools list [OR-481]
  data/links.yaml
  data/navigation.yaml
Labels: release:minor

#855 correct ft app link
  data/links.yaml
Labels: service, release:minor
